apiVersion: v1
kind: Secret
metadata:
  name: auth-mysql
type: Opaque
data:
  mysql-root-password: {{ .Values.secret.mysqlRootPassword | b64enc }}
  mysql-password: {{ .Values.secret.mysqlPassword | b64enc }}
  mysql-replication-password: {{ .Values.secret.mysqlReplicationPassword | b64enc }}