apiVersion: v1
kind: Secret
metadata:
  name: auth-mongodb
type: Opaque
data:
  mongodb-passwords: {{ .Values.secret.mongodbPasswords | b64enc }}
  mongodb-root-password: {{ .Values.secret.mongodbRootPassword | b64enc }}
  mongodb-metrics-password: {{ .Values.secret.mongodbMetricsPassword | b64enc }}
  mongodb-replica-set-key: {{ .Values.secret.mongodbReplicaSetKey | b64enc }}