apiVersion: v1
kind: Secret
metadata:
  name: auth-minio
type: Opaque
data:
  minio_root_user: {{ .Values.secret.minioRootUser | b64enc }}
  minio_root_password: {{ .Values.secret.minioRootPassword | b64enc }}