apiVersion: v1
kind: Secret
metadata:
  name: auth-rabbitmq
type: Opaque
data:
  rabbitmq-password: {{ .Values.secret.rabbitmqPassword | b64enc }}
  rabbitmq-erlang-cookie: {{ .Values.secret.rabbitmqErlangCookie | b64enc }}